name: linwood_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  args: ^2.3.0
  dotenv: ^3.0.0
  nyxx: ^3.2.0
  nyxx_interactions: ^3.1.0
